const ERROR = {
    NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
    INVALID_OR_EXPIRED_TOKEN: "INVALID_OR_EXPIRED_TOKEN_PROVIDED",
    INVALID_TOKEN_PROVIDED: "INVALID_TOKEN_PROVIDED",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    BAD_REQUEST: "BAD_REQUEST",
    NOT_FOUND: "NOT_FOUND",
};
export default ERROR;
