const USER = {
    USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INCORRECT_CREDENTIALS: "INCORRECT_CREDENTIALS",
    REGISTRATION_COMPLETED: "REGISTRATION_COMPLETED",
    PORFILE_DETAILS_NOT_FOUND: "PROFILE_DETAILS_NOT_FOUND",
};
export default USER;
